version: "3"

services:
  app:
    build: .
    image: app:rubik
    ports:
      - "5000:5000"
    command: ["python","main.py"]
    volumes: 
      - app-volume:/app
  cron_arquivo:
    image: app:rubik
    command: ["python","-u","cronArquivos.py"]
    volumes: 
      - app-volume:/app
    depends_on: 
      - app
  # cron_robo:
  #   image: app:rubik
  #   command: ["python","-u","cronRobo.py"]
  #   volumes: 
  #     - app-volume:/app
  #   depends_on: 
  #     - app

volumes:
  app-volume: